### Get all events
GET http://localhost:8080/events

### Get a single event
GET http://localhost:8080/events/13

### Create a new event
POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsImV4cCI6MTczNjc1Njk1OSwidXNlcklEIjo1fQ.UXXyeP2KH2HoDcektsvEZF_n3gTu5MFZxsBItog9_QA

{
  "title": "Test user Event",
  "description": "This is a test event",
  "datetime": "{{$datetime iso8601}}",
  "location": "Test Location"
}

### Incomplete request body
POST http://localhost:8080/events
Content-Type: application/json

{
  "title": "Bad Event",
  "description": "This is a bad event. No location or datetime"
}

### Empty request body
POST http://localhost:8080/events
Content-Type: application/json

{ }


### Update an event
PUT http://localhost:8080/events/13
Content-Type: application/json

{
  "title": "Updated Event",
  "description": "This is an updated event",
  "datetime": "{{$datetime iso8601}}",
  "location": "Updated Location"
}

### Update an event with invalid id
PUT http://localhost:8080/events/13a
Content-Type: application/json

{
  "title": "Updated Event",
  "description": "This is an updated event",
  "datetime": "{{$datetime iso8601}}",
  "location": "Updated Location"
}

### Update an event with incomplete request body
PUT http://localhost:8080/events/13
Content-Type: application/json

{
  "title": "Updated Event",
  "location": "Updated Location"
}

### Delete a single event
DELETE http://localhost:8080/events/16

### Delete an event with invalid id
DELETE http://localhost:8080/events/16a